- src: https://github.com/dayglo/ansible-role-ovftool
- src: https://github.com/dayglo/ansible-role-vmware-workstation 
- src: https://github.com/geerlingguy/ansible-role-nodejs
- src: https://github.com/dayglo/ansible-teamcity-agent